# --- Archivo: .github/workflows/ci.yml (Actualizado) ---
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Tests
    env:
      AIRTABLE_API_KEY: test
      AIRTABLE_BASE_ID: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install backend dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Check for missing dependencies
        run: |
          cd backend
          python check_missing_deps.py


      - name: Run backend tests
        run: |
          cd backend
          pytest -q

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

      # ✅ NUEVO PASO: Añadimos la verificación de código aquí
      - name: Lint Code
        run: |
          cd frontend
          npm install
          npm run lint

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build